---

- name: "Tuning all nodes"
  hosts: all
  gather_facts: true
  tasks:
    - name: "Display all hostnames"
      debug:
        msg: "The hostname is {{ ansible_hostname }} and the OS is {{ ansible_os_family }}"

    - name: "Update /etc/hosts file"
      blockinfile:
        dest: /etc/hosts
        content: "{{ lookup('template', 'hosts.j2') }}"
        state: present

- name: "Tuning db nodes"
  hosts: db
  vars_files: 
  - ./group_vars/credentials
  roles:
    - common
#    - pgdocker
