---
# tasks file for common

- name: Change ssh_config parameter StrictHostKeyChecking to no
  lineinfile:
    path: /etc/ssh/ssh_config
    regexp: '^StrictHostKeyChecking'
    line: 'StrictHostKeyChecking = no'
    state: present
  tags: common

#- include_tasks: storage.yml

- name: "Install system packages"
  apt:
    name: "{{ packages }}"
    force_apt_get: true
    update_cache: yes
  vars:
    packages:
    - telnet
    - nmon
    - nmap
    - curl
    - wget
    - strace
    - ca-certificates
  tags: common

