---
# tasks file for libvirt
- name: "Install  libbvirt-kvm packages"
  apt:
    name: "{{ packages }}"
    force_apt_get: true
    update_cache: yes
  vars:
    packages:
    - git
    - nmap
    - qemu-kvm
    - libvirt-daemon-system
    - libvirt-clients
    - libnss-libvirt
    - bridge-utils
    - uvtool
    - uvtool-libvirt
    - dnsmasq
    - ebtables
    - cpu-checker
    - libguestfs-tools
  tags: kvm

- sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
  tags: kvm

- name: "Add user libvirtadmin"
  user:
    name: "{{ libvirt_user }}"    
    password: "{{ libvirt_pass | password_hash('sha512') }}"
    shell: /bin/bash
    groups: sudo,libvirt
    append: yes
    state: present
  tags: kvm

- name: "Make sure the iso directory exists"
  file:
    path: "{{ iso_dir }}"
    state: directory
    mode: 0700
  tags: kvm

- name: "The copy nsswitch.conf"
  template:
    src: "nsswitch.conf.j2"
    dest: "/etc/nsswitch.conf"
    mode: 0644
  tags: kvm

