---

- name: "Tuning all nodes"
  hosts: all
  gather_facts: true
  tasks:
    - name: Display all hostnames 
      debug:
        msg: "The hostname is {{ ansible_hostname }} and the OS is {{ ansible_os_family }}"

- name: "Tuning db nodes"
  hosts: db
  roles:
    - common
