---
# tasks file for common

- name: "Change ssh_config parameter StrictHostKeyChecking to no"
  lineinfile:
    path: /etc/ssh/ssh_config
    regexp: '^StrictHostKeyChecking'
    line: 'StrictHostKeyChecking = no'
    state: present
  tags: common

# You can specify multiple pvs separated by commas
- name: "Create the volume group for /dev/sdb"
  lvg:
    vg: "{{ vg }}"
    pvs: /dev/sdb
    state: present
  tags: common

- name: "Create the logical volume in the volume group"
  lvol:
    vg: "{{ vg }}"
    lv: "{{ lv }}"
    size: +100%FREE
    resizefs: true
    state: present
  tags: common

- name: "Create FS for logical volume"
  filesystem:
    fstype: "{{ fs }}"
    dev: "/dev/mapper/{{ vg }}-{{ lv }}"
    force: no
  tags: common

- name: "Create a directory for mount point"
  file:
    path: "{{ mount_point }}"
    state: directory
    mode: '0755'
  tags: common

- name: "Mount filesystem to mount point"
  mount:
    path: "{{ mount_point }}"
    src: "/dev/mapper/{{ vg }}-{{ lv }}"
    fstype: "{{ fs }}"
    opts: rw,nosuid,noexec
    state: mounted
  tags: common

- name: "Install system packages"
  apt:
    name: "{{ packages }}"
    force_apt_get: true
    update_cache: yes
  vars:
    packages:
    - telnet
    - nmon
    - nmap
    - curl
    - git
    - wget
    - strace
    - ca-certificates
    - apt-transport-https
    - software-properties-common
    - python3-pip
    - virtualenv
    - python3-setuptools
  tags: common,docker

- name: "Add Docker GPG apt key"
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags: common,docker

- name: "Add Docker Repository"
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu bionic stable
    state: present
  tags: common, docker

- name: "Update apt and install docker-ce"
  apt: 
    update_cache: yes
    name: docker-ce
    state: latest
  tags: common,docker

- name: "Install Docker Module for Python"
  pip:
    name: docker
  tags: common,docker

- name: "Install docker-compose"
  get_url: 
    url : https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'
  tags: common,docker
