---
# tasks file for pgdocker
- name: "Create repos directory"
  file:
    path: "{{ repos }}"
    state: directory
    mode: 0700
  tags: pg
  
- name: "Clone repos for building and configuring images"
  git:
    repo: "{{ item.repos }}"
    dest: "{{ repos }}/{{ item.reponames }}"
    clone: yes
    update: no
  with_items:
  - { repos: 'https://github.com/xcrezd/pg-dock.git', reponames: 'pg-dock' }
  - { repos: 'https://github.com/xcrezd/pg-dock-conf.git', reponames: 'pg-dock-conf' }
  - { repos: 'https://github.com/xcrezd/pg-dock-base.git', reponames: 'pg-dock-base' }
  tags: pg
